### ISSUE TITLE
Merge Pull Requests

### ISSUE THREAD

**Issue by jamesgoodhouse** [terraform-providers/terraform-provider-newrelic#179]
What is the best way to move forward with some of the PRs that are piling up? I'm more than happy to take the reins on this if possible so we can unblock some of these. Thanks!

**Comment by pwillis-els** [comment]
Seconding this...

**Comment by morganchristiansson** [comment]
Yeah it looks like there's some important PRs pending.. How can the community help?

**Comment by sanderblue** [comment]
@morganchristiansson Can you link us to some of the important pending PRs that are on your mind? This will help us prioritize some of these. Much appreciated. 😃

**Comment by morganchristiansson** [comment]
I've specifically ran into some sort of bug in #182 

PRs to add NRQL could allow me to workaround the bug by providing an alternative to where attribute which is not working correctly for me.

PRs to update newrelic library or dependencies may help if the bug is from using recent features. (I saw some warnings about legacy API using terraform v0.12.9 but they seem to no longer be logged after upgrading terraform to 0.12.12)

**Comment by sanderblue** [comment]
Thank you for the feedback. This at least helps to identify some pain points.

**Comment by ctrombley** [comment]
We at New Relic are currently working to shore up some of the existing debt.  You can expect more focus and attention on these issues going forward.  Closing this issue for now.
