### ISSUE TITLE
Alerts for Plugin Conditions

### ISSUE THREAD

**Issue by Thadir** [terraform-providers/terraform-provider-newrelic#47]
Good day,,

We started to maintain our configuration of New Relic in terraform, and up to now with the plugin version 1.0.1 its working great. However, we created some new relic plugins that provide custom metrics and I want to create custom alerts on these metrics:

The api is available:
https://docs.newrelic.com/docs/alerts/rest-api-alerts/new-relic-alerts-rest-api/rest-api-calls-new-relic-alerts#plugins-conditions but I cannot find if this feature is in the documentation.

**Comment by bridgetlane** [comment]
Hi @Thadir! Terraform is an open source project and as such providers like this are largely supported by the community and contributors. This means that not every single API call in the New Relic API is currently available. If you contribute/make a pull request for the additional functionality you want I would be happy to review it. Otherwise please make this issue more clear with the functionality you are requesting it and label it 'help wanted'.

**Comment by atrepca** [comment]
I might have bumped into the same limitation, so I'll try to describe: when adding an alert condition you can select the 'Plugins' product, then the type of plugin, like below:
<img width="692" alt="screen shot 2018-10-22 at 11 57 55 pm" src="https://user-images.githubusercontent.com/2030087/47319184-afd05e00-d656-11e8-9925-0b7f3aa4781e.png">
Currently `type` can be one of: `apm_app_metric, apm_jvm_metric, apm_kt_metric, servers_metric, browser_metric, mobile_metric`, so no plugins.

**Comment by bridgetlane** [comment]
@atrepca yup thats going to have to be a feature addition - added the 'help wanted' label to this.

**Comment by maikelmertens** [comment]
I'm too eagerly wanting this feature request implemented as we are working with some NewRelic plugins and defined alerts on it.

Although we want to automate and define it within code, this unfortunately isn't possible yet.

**Comment by ctrombley** [comment]
Resolved by #234 .
