### ISSUE TITLE
NewRelic Memory Alert Condition Issue

### ISSUE THREAD

**Issue by selvan1978** [terraform-providers/terraform-provider-newrelic#589]
**Terraform Version**

Terraform v0.12.24

**NewRelic Proider Version**

provider.newrelic v1.18.0

**Affected Resource(s)**

newrelic_infra_alert_condition

**Error Message**

![image](https://user-images.githubusercontent.com/53402695/82407818-cc798580-9a87-11ea-980c-e7e75d8c1e83.png)

**Terraform Configuration Files**

resource "newrelic_infra_alert_condition" "high_memory" {
	policy_id = newrelic_alert_policy.testpolicy.id
	name       = "Test Memory Alert"
	type       = "infra_metric"
	event      = "SystemSample"
	select     = "memoryUsedPercent"
	comparison = "above"
	where      = "(`hostname` LIKE '%prod%')"
	critical {
		duration      = 15
    value         = 90
    time_function = "all"
	}
}

Thanks,
Selvan.

**Comment by sanderblue** [comment]
Hi @selvan1978, thanks for opening an issue. Is this a bug report? I tested your example configuration, but wasn't sure what to look for. Running `terraform plan` and `terraform apply` with your configuration worked as expected. Are you seeing errors when running `terraform apply`?

**Comment by selvan1978** [comment]
Thanks for your reply. I dont see any issues during terraform plan and terraform apply. Memory alert condition also configured successfully but when i checked the memory alert condition, it shows this error **_"You selected memoryUsedPercent as the metric for this alert. This metric is not available through the New Relic UI"_** and no chart data available. Please find below screen shot.

![image](https://user-images.githubusercontent.com/53402695/82533225-7c222680-9b60-11ea-8e9b-84fd45de5406.png)

I have configured similar for CPU spike and looks good.

![image](https://user-images.githubusercontent.com/53402695/82533469-f2268d80-9b60-11ea-8c35-777e997e094d.png)

**Comment by sanderblue** [comment]
Thanks for clarifying. I was able to reproduce the issue as well. This is a weird one because the select dropdown has `Memory Used %` as an option if I create a new alert condition from the UI, however it maps to a different `select` value. 

From what I can tell, I think you need to use [`memoryUsedBytes/memoryTotalBytes*100`](https://docs.newrelic.com/docs/infrastructure/new-relic-infrastructure/infrastructure-alert-conditions/rest-api-calls-new-relic-infrastructure-alerts#definitions) for your `select` value (scroll down to `select_value` in the docs for some addition information).

Example:

```hcl
resource "newrelic_infra_alert_condition" "high_memory" {
  policy_id  = newrelic_alert_policy.testpolicy.id
  name       = "Test Memory Alert"
  type       = "infra_metric"
  event      = "SystemSample"
  select     = "memoryUsedBytes/memoryTotalBytes*100"
  comparison = "above"
  where      = "(hostname LIKE '%prod%')"
  critical {
    duration      = 15
    value         = 90
    time_function = "all"
  }
}
```
We can do a better job with preventing this sort of confusion with better validation, so thanks for reporting. 

Please try `memoryUsedBytes/memoryTotalBytes*100` and feel free to let us know if that works for you. Thanks!

**Comment by selvan1978** [comment]
Thanks for your help. I have changed select value to **_memoryUsedBytes/memoryTotalBytes*100_** and able to see chart data now.

![image](https://user-images.githubusercontent.com/53402695/82724322-d652f100-9cf2-11ea-8c79-ad3093d12a86.png)
